sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.8
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem install bundler
script:
  - echo 'no test yet'

